# Generated by Django 5.2.5 on 2025-08-24 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourist_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='description',
            field=models.CharField(max_length=10000),
        ),
    ]
